### PR TITLE
✨ Add apiextensions clients

### PR DESCRIPTION
**Pull request by sttts**
We currently generate these into our Kube branch. This PR adds those clients, informers and listers into client-go.

Unfortunately, we did not put the kubernetes packages under kubernetes (similarly to Kube's client-go). So this is a little off, or rather kube is a little off.

### CODE REVIEW

**Review by embik — APPROVED** [review]
/approve

**Comment by mjudeikis** [comment]
/lgtm
/approve
nice one!

**Comment by sttts** [comment]
`level=error msg="Timeout exceeded: try increasing it by passing --timeout option"` 😔

**Pull request merged**
